-- Create table
create table CONTACT
(
  ID int(10) unsigned not null AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  SURNAME VARCHAR(255) NOT NULL,
  PATRONYMIC VARCHAR(255),
  DATE_OF_BIRTH DATE,
  GENDER    VARCHAR(1),
  NATIONALITY VARCHAR(255),
  MARITAL_STATUS  VARCHAR(30),
  WEB_SITE VARCHAR(255),
  EMAIL VARCHAR(255),
  WORK_PLACE VARCHAR(255),
  COUNTRY VARCHAR(255),
  CITY VARCHAR(255),
  ADDRESS VARCHAR(255),
  ZIP_CODE VARCHAR(255),
  IMAGE LONGBLOB,
  primary key (ID)
);
-- Create table
create table NUMBER
(
  ID int(10) unsigned not null AUTO_INCREMENT,
  CONTACT_ID int(10) unsigned not null REFERENCES CONTACT (ID),
  COUNTRY_CODE VARCHAR(30),
  OPERATOR_CODE VARCHAR(30),
  NUMBER VARCHAR(30),
  TYPE  VARCHAR(30),
  COMMENT  VARCHAR(255),
  primary key (ID)
);
-- Create table
CREATE TABLE ATTACHMENT (
    ID INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    CONTACT_ID INT(10) UNSIGNED NOT NULL REFERENCES CONTACT (ID),
    NAME VARCHAR(255),
    DATE DATETIME,
    COMMENT VARCHAR(255),
    PRIMARY KEY (ID)
);
